# Generated by Django 2.1 on 2019-08-15 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemploapp', '0002_auto_20190815_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejemplar',
            old_name='id_libro',
            new_name='libro',
        ),
    ]
