# Generated by Django 2.1 on 2019-08-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemploapp', '0004_auto_20190815_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.BooleanField(),
        ),
    ]
