# Generated by Django 2.1 on 2019-08-15 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejemploapp', '0005_auto_20190815_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejemplar',
            name='fechadecompra',
            field=models.DateField(max_length=45),
        ),
    ]
