# Generated by Django 2.1 on 2019-08-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemploapp', '0008_auto_20190815_1756'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='isbn',
            new_name='ISBN',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='copiar',
        ),
    ]
