# Generated by Django 2.1 on 2019-08-20 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemploapp', '0009_auto_20190820_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejemplar',
            old_name='numeroejemplar',
            new_name='numeroejemplaer',
        ),
    ]
